name: Deploy HackTree Pages

on:
    pull_request:
      branches: pages
      types:
        - closed

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Fastn
        run: sh -c "$(curl -fsSL https://fastn.io/install.sh)"

      - name: Run Node.js Script
        run: npm run build:pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
      - name: Update .hash.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./.hash.json
          git commit -m "Updated .hash.json"
          git remote remove origin
          git remote add origin https://harshdoesdev:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/harshdoesdev/hacktree.git
          git push origin HEAD:pages
        
